# Generated by Django 4.2.1 on 2025-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='bitrix_deal_id',
        ),
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
