# Generated by Django 4.2.1 on 2025-03-22 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0002_remove_deal_bitrix_deal_id_alter_deal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.DateTimeField()),
                ('name', models.CharField(db_index=True, default=None, max_length=250, null=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
