# Generated by Django 4.2.1 on 2025-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0002_remove_deal_bitrix_deal_id_alter_deal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user_review',
            field=models.TextField(default=None, max_length=200, null=True, verbose_name='Отзыв пользователя'),
        ),
    ]
