# Generated by Django 4.2.1 on 2025-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0003_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
    ]
